jta tck release notes
eclipse-ee4j/jakartaee-tck pull request #556
Opened 2020-10-27 11:29 UTC by alwin-joseph

2020-10-27 14:02 UTC, scottmarlow commented
:+1:

2020-10-30 15:58 UTC, gurunrao approved these changes

2020-10-30 16:09 UTC, scottmarlow approved these changes

2020-11-04 14:24 UTC, hussainnm requested changes
Shouldn't JTA be replaced with Jakarta Transactions?

2020-11-04 15:13 UTC, scottmarlow commented
> Shouldn't JTA be replaced with Jakarta Transactions?

Yes, you are correct.

2020-11-18 10:06 UTC, closed without merging