#625 Fix for 2 standalone servlet tests failing in jdk11
eclipse-ee4j/jakartaee-tck pull request #637
Opened 2021-03-06 15:31 UTC by arjantijms

This updates the GF specific principal to role mapping to use RFC 2253
formatting for the DN, and for the client-cert test sets TLSv1.2 as an
option for JDK 11.

---
name: Pull Request
about: Create a pull request for a Platform TCK change
title: 'Fix for 2 standalone servlet tests failing in jdk11'
labels: ''
assignees: ''

---

**Fixes Issue**
https://github.com/eclipse-ee4j/jakartaee-tck/issues/625

**Related Issue(s)**
Specify any related issue(s) links.

**Describe the change**
This updates the GF specific principal to role mapping to use RFC 2253
formatting for the DN, and for the client-cert test sets TLSv1.2 as an
option for JDK 11.

**Additional context**
https://www.eclipse.org/lists/glassfish-dev/msg00967.html

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman

Signed-off-by: arjantijms <arjan.tijms@gmail.com>

2021-03-07 14:02 UTC, scottmarlow approved these changes

2021-03-07 14:02 UTC, scottmarlow commented
@markt-asf @stuartwdouglas could you please review this change.  Thank you! 

@arjantijms thank you for the fix!

2021-03-08 09:14 UTC, markt-asf requested changes
LGTM with some minor fixes.

I wonder about shipping container (Glassfish) specific configuration files in the TCK but this isn't the venue for that discussion.

2021-03-08 09:14 UTC, markt-asf commented on install/servlet/bin/ts.jte.jdk11
>  ###################################################################
Copyright date needs to be updated

2021-03-08 09:14 UTC, markt-asf commented on src/com/sun/ts/tests/servlet/spec/security/clientcert/Client.java
Copyright date needs to be updated.

2021-03-08 09:14 UTC, markt-asf commented on src/com/sun/ts/tests/servlet/spec/security/clientcertanno/Client.java
Copyright date needs to be updated.

2021-03-08 12:31 UTC, arjantijms commented
On Mon, Mar 8, 2021 at 10:15 AM Mark Thomas <notifications@github.com>
wrote:

> *@markt-asf* requested changes on this pull request.
>
> LGTM with some minor fixes.
>
> I wonder about shipping container (Glassfish) specific configuration files
> in the TCK but this isn't the venue for that discussion.
>
I agree with both statements. We (the GF and TCK teams) should work, in
another discussion, to move the GlassFish specific configuration files to a
GlassFish porting kit.




> ------------------------------
>
> In install/servlet/bin/ts.jte.jdk11
> <https://github.com/eclipse-ee4j/jakartaee-tck/pull/637#discussion_r589268154>
> :
>
> > @@ -309,6 +309,13 @@ authpassword=javajoe
>  ###############################################################
>  securedWebServicePort=
>
> +###############################################################################
> +# @client.cert.test.jdk.tls.client.protocols JDK 11 in TLSv1.3 does not support
> +#                        Post-Handshake Authentication, so TLSv1.2 must be used
> +#                        for client-cert authentication to work.
> +###############################################################################
> +client.cert.test.jdk.tls.client.protocols=TLSv1.2
> +
>  ###################################################################
>
> Copyright date needs to be updated
>
Ah, thanks. How could I forget this. I'll update it right away. Thanks!

Kind regards,
Arjan




> ------------------------------
>
> In src/com/sun/ts/tests/servlet/spec/security/clientcert/Client.java
> <https://github.com/eclipse-ee4j/jakartaee-tck/pull/637#discussion_r589269549>
> :
>
> > @@ -117,6 +125,10 @@ public void clientCertTest() throws Fault {
>      String testName = "clientCertTest";
>      String url = ctsurl.getURLString("https", hostname, portnum,
>          pageBase + authorizedPage);
> +
> +    if (tlsVersion != null) {
> +        System.setProperty("jdk.tls.client.protocols", tlsVersion);
> +    }
>
>
> Copyright date needs to be updated.
> ------------------------------
>
> In src/com/sun/ts/tests/servlet/spec/security/clientcertanno/Client.java
> <https://github.com/eclipse-ee4j/jakartaee-tck/pull/637#discussion_r589269808>
> :
>
> > @@ -128,6 +136,10 @@ public void clientCertTest() throws Fault {
>      String testName = "clientCertTest";
>      String url = ctsurl.getURLString("https", hostname, portnum,
>          pageBase + authorizedPage);
> +
> +    if (tlsVersion != null) {
> +        System.setProperty("jdk.tls.client.protocols", tlsVersion);
> +    }
>
>
> Copyright date needs to be updated.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eclipse-ee4j/jakartaee-tck/pull/637#pullrequestreview-606087359>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXFOTXFWEEJDBHUA5WU7X3TCSIR7ANCNFSM4YW2RQ6A>
> .
>

2021-03-08 15:07 UTC, scottmarlow commented
>  I wonder about shipping container (Glassfish) specific configuration files in the TCK but this isn't the venue for that discussion.
> I agree with both statements. We (the GF and TCK teams) should work, in another discussion, to move the GlassFish specific configuration files to a GlassFish porting kit.

+100

2021-03-08 15:07 UTC, merged